### ISSUE TITLE
Add toggle in notification

### ISSUE THREAD

**Issue by 35609902357** [kaputnikGo/PilferShushJammer#13]
The notification should contain a quick toggle to activate/deactivate the jammer to allow toggling quickly before an event where the mic use is needed suddenly and urgently, like answering a call

**Comment by kaputnikGo** [comment]
The app will automatically get bumped off the mic when a system call is received. If you mean for VoIP then thats a pretty good idea.

**Comment by kaputnikGo** [comment]
new release build available here (google play, fdroid when they do publish) that has passive jammer off switch in notification view.
thanks for the suggestion.

**Comment by 35609902357** [comment]
Can this be made with a persistent notification to pause/resume the service as long as the jammer is enabled, for an easy transition when the mic is needed (e.g. send a quick vocal message without coming back to the home screen and launch the app whenever such an occurrence happens)?
