### ISSUE TITLE
Needs a whitelist, like a firewall for the microphone.

### ISSUE THREAD

**Issue by Innomen** [kaputnikGo/PilferShushJammer#14]
A lot more people would use this if it behaved like a firewall.

**Comment by kaputnikGo** [comment]
AFAIK it is not possible to identify the process that is either attempting to gain or has gained microphone access other than via adb type (root level) checks. This isn't practical or even feasible for PilferShush considering the broad range of devices that it covers.

So the alternative would be to list all installed apps and then constantly poll the OS for when a particular app was bought to the foreground and whether it appears on the whitelist or not. But even then there is no guarantee that the app making the request is the one actually gaining access at that time.

If that is the sort of app level control you desire then I think revoking microphone permissions for apps you dont want to use the microphone is the OS preferred method.
