### ISSUE TITLE
No scolling

### ISSUE THREAD

**Issue by command32** [kaputnikGo/PilferShushJammer#15]
Using android 7 with a small screen the record lock does not show under the settings tab. Verify it is presented out of visible range of small screens then add scrolling.

**Comment by kaputnikGo** [comment]
Ok thanks for the info. I have an updated build with scrollbar now and will compile and push to stores in a couple of days.

**Comment by kaputnikGo** [comment]
Ok have uploaded the updated release here (github) and to the google play store. FDroid will auto update in a day or so. I added the scrollview to the settings view but am unable to test in an actual device (can only use the emulator). Hopefully this works for you.
thanks again.
