### ISSUE TITLE
Better Documentation, Start on Reboot, Save Settings On Reboot

### ISSUE THREAD

**Issue by grravity** [kaputnikGo/PilferShushJammer#19]
Pilfer doesn't start automatically on reboot, and it doesn't save settings on reboot.

Also I think clearer documentation on exactly what each setting does, the benefit or disadvantage of using one setting or one vs another, and how that feature protects you, what it protects you from, and what it doesn't protect you from-is highly needed.

**Comment by kaputnikGo** [comment]
Currently I'm undecided about "consider optional jammer state persistence over boot". This app started out as experimental uni research into near-ultra high frequency audio but it now seems that enough people want to rely on it for constantly jamming the mic and boot persistence seems to be a thing.

And yeah, better documentation about the processes needs to be freely and publicly available outside of the source code files. So thats being worked on now.

**Comment by grravity** [comment]
> but it now seems that enough people want to rely on it for constantly jamming the mic and boot persistence seems to be a thing.

Yeah, I mean if there's a need to seperate them, you could just make a seperate app (with quite honestly a better name), seperate the two, and the latter does the job specifically of jamming the mic, boot persistance, and overall a more privacy focused app. Just an idea if you needed though :)

**Comment by kaputnikGo** [comment]
No separate app, its enough to maintain this one and the 1700 devices it currently targets. I am looking into boot persistence but it looks messy, so not sure yet. 
Also, this app couldn't be any more privacy focused as it has open source code that is commented where needed, FDroid builds and signs their own apk, requests only the bare minimum permissions to hold the mic (Record Audio and Foreground Service) and NO suspect permissions such as Internet, Storage (for writing audio files), Accounts etc.

**Comment by kaputnikGo** [comment]
adding a readme to the app (4.3.1 release soon) which should provide more generalised information about the functions of the jammers, and also provides a link to the project webpage that has lots of info, research, images and NUHF audio example.

**Comment by grravity** [comment]
Thank you!

**Comment by kaputnikGo** [comment]
finally getting around to adding boot receiver and auto restart at boot with settings for next release 4.5.0

**Comment by kaputnikGo** [comment]
this may not work as expected. updates to the boot autostart will be posted to this issue : https://github.com/kaputnikGo/PilferShushJammer/issues/21
