### ISSUE TITLE
Possibility to add video protection?+ question about battery

### ISSUE THREAD

**Issue by WPFilmmaker** [kaputnikGo/PilferShushJammer#22]
First of all thank you for your work! I was wondering whether you could add jamming also for cameras, in the same way as the jammer works for mics. Also a question, since the jammer runs constantly, does it drain the battery?

**Comment by kaputnikGo** [comment]
Adding a camera jammer was considered sometime ago, its relatively straightforward to implement if a bit OP, but recent changes to the Android API mean that function is not possible from Android 9 onwards:

"Device Admin feature USES_POLICY_DISABLE_CAMERA is deprecated in Android 9 and will stop working with a Security Ex error in Android 10"

The jammer app does no processing, no listening to audio, no copying buffers and no writing to disk when it runs and so it uses no battery. However, the OS uses battery to keep the background jammer service running, as it would do for any app running a background service. Also the microphone at the hardware device level is performing an analogue to digital conversion with a signal path that ends at the underlying selinux level.

My tests on a LineageOS Samsung 5 have shown battery drain comparable to general Android OS/Android system battery drain over prolonged periods of time. Your results may vary depending on the flavour of Android you are running and the make/model of phone etc.
