### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by c-4-m** [kaputnikGo/PilferShushJammer#26]
Hi, I want to contribute to this great project by providing a german translation.

I have forked the current master branch and will send a pull request when I have something presentable.

Sadly I dont have much experience with android apps, so do I need to change anything other than creating a directory "values-de" with a translated strings.xml?

Best Regards

**Comment by kaputnikGo** [comment]
Brilliant! vielen Dank! and yes thats all you need to do - a vlaue-de folder with strings.xml

**Comment by c-4-m** [comment]
Could you please explain the "record buffer lock" mechanism? I dont want to convey the wrong message :)

**Comment by kaputnikGo** [comment]
In an attempt to get battery use to a minimum i figured that at a minimum a call needs to be made to audioRecord.startRecording(); which doesn't actually record, it just initialises the AudioRecord object. This is the current default behaviour for the PilferShush passive jammer. According to the Android API and testing on devices and emulators, this method is enough to lock up the microphone from other user apps using it.

If someone didnt think that was reliable enough for their device then they could switch the "record buffer lock" to on and this would make the passive jammer access the microphone hardware audio buffer and copy it to an unused array. This is how the passive jammer originally worked before battery optimisation became necessary as people were using the jammer for long periods of time. 

Hopefully this makes sense. 
The code is here : https://github.com/kaputnikGo/PilferShushJammer/blob/70566aa59260f8f0c655b22bcda784957e1e76a0/app/src/main/java/cityfreqs/com/pilfershushjammer/jammers/PassiveJammer.java#L70

Let me know if you need any other info,
thanks again!

**Comment by c-4-m** [comment]
Hi, 
sorry for the long silence, Life happened.

So I have ~80-90% of the strings translated but the last ones are somewhat tough to get exactly right. 

Do you want me to open a pull request with the translation as of now, so that I or someone else can perfect it later?

**Comment by kaputnikGo** [comment]
hi there, thats not a problem, life always happens :)
yes if you would like to make pr then i can roll out the release.
thanks for taking the time to do this!
