### ISSUE TITLE
Notification tray not showing

### ISSUE THREAD

**Issue by Lumb-Chul** [kaputnikGo/PilferShushJammer#3]
I've downloaded pilfershush from Fdroid. Running9n a Galaxy s9 a notification is not created when put on passive mode.
Are notifications supported in thelatest version?

**Comment by kaputnikGo** [comment]
A notification is posted immediately upon successfully starting passive mode. Passive mode requires access to the microphone and to start an AudioRecord object. Also, the UI text reports "Passive Jammer init.", "Passive Jammer start." and finally "Running passive jamming..." to indicate success.
