### ISSUE TITLE
Passive Mode on Phone's Startup

### ISSUE THREAD

**Issue by PedroBarcha** [kaputnikGo/PilferShushJammer#4]
Currently, is there a way to make PilferShush initialize its passive mode on the phone's startup?

**Comment by kaputnikGo** [comment]
No. I think that should be a user choice as the passive technique of grabbing the microphone and holding it is intended to block other user apps from accessing it. This is something that should not be relied upon for long periods of time as it is not really a "fix" but a brute response used to demonstrate an existing problem with Android phones - you cannot really be certain that any given app with the required permissions is not using the microphone to record audio from a background process.

The technique doesn't use any extra CPU cycles as there is no audio buffer copying. But i cannot test its behaviour with VoIP apps for instance, so your results may vary.

Future versions may include a background scanner that goes through the user app list and checks for services, receivers, boot start, record audio abilities and known NUHF beacon SDKs. This may help in determining whether your phone needs the jammer.
