### ISSUE TITLE
F-Droid metadata path incorrect

### ISSUE THREAD

**Issue by linsui** [kaputnikGo/PilferShushJammer#41]
The path should be fastlane/metadata/android/en-US or metadata/en-US. Could you please fix it? Thanks!

**Comment by kaputnikGo** [comment]
aight, duped the en-AU folder to US

**Comment by linsui** [comment]
The problem is that the current path is `metadata/android/` but we need either `fastlane/metadata/android/` or `metadata/`.

**Comment by kaputnikGo** [comment]
lol. ok.

**Comment by linsui** [comment]
Thanks!
