### ISSUE TITLE
(Feature) Please add Integration with Tasker

### ISSUE THREAD

**Issue by soilentgreen** [kaputnikGo/PilferShushJammer#45]
First of all want to sat thank you  for this awesome app. I locking a long time for app like that.

About Tasker. If your app will be Integrate with Tasker, a lot of things can be reach:

We could add quick settings for toggles Passive/Active.
We could start the service after reboot.
We could start/end the service when we open any app (like singal).
We could start/end the service in specific time or date... and so on.

Integrate your app with Tasker make the options endless, and the app then will be more awesome than it today.
I’m very very hope you decide to make it. (I use note 8 with pie)

**Comment by kaputnikGo** [comment]
no, there will be no integration with any framework that isnt part of the AOSP API
