### ISSUE TITLE
Issue with headphones

### ISSUE THREAD

**Issue by soilentgreen** [kaputnikGo/PilferShushJammer#47]
I have a weird Issue. When I  connect  headphones to my phone, the service (I use passive) stop, than after a few seconds it start again, and when I disconnects them, the service stop and never restart.
App Version: 4.6.1
Android Version: 9
Battery Optimization is turned off

Hope it can fix.
Thanks.

**Comment by kaputnikGo** [comment]
yeah i dont think it was coded to do that because its meant to be a one off resume. the design is to be mostly a manually controlled app, automation would be need to make assumptions that wouldn't fit all use-cases or the app design.
