### ISSUE TITLE
volume goes to maximum when 'passive' jamming is active

### ISSUE THREAD

**Issue by puppykickr** [kaputnikGo/PilferShushJammer#6]
I dont know if this is a requirement of function, but when the passive jammer is activated, the volume of the device immediately goes to max.

I understand why this is needed for the active jammer to operate, but not the passive.

**Comment by kaputnikGo** [comment]
There is a headphone connection listener that is supposed to mute output at certain times. I have noticed this is inconsistent across various APIs, so this will be reworked in the next major release.

**Comment by puppykickr** [comment]
Great. I will wait to see what you come up with.

Is there also going to be an addition to include the camera(s), either front, back, or both?

This could also prove to be useful.

**Comment by kaputnikGo** [comment]
update pushed to google play and f-droid.

**Comment by kaputnikGo** [comment]
Excellent!
