### ISSUE TITLE
app will not turn off completely

### ISSUE THREAD

**Issue by puppykickr** [kaputnikGo/PilferShushJammer#7]
After I turn both jammers off, the notification is still on, and telling me that the app is active.

Even when I clear the app from the app manager, the notification remains.

An 'off' button, in the app or part of the notification, or even just being able to use the app manager to cease all app functions would be great.

**Comment by kaputnikGo** [comment]
what device and os version (rom?) are you using?
Notifications are in the process of being re-written as android changes things a bit in API 28 and the whole behaviour is not working as intended. For example, the intention was that notifications stay to inform the user that a process is running in the background, but this is pointless when the os allows the user to permanently dismiss notifications.

**Comment by kaputnikGo** [comment]
Unfortunately your use case is the opposite of the designed behaviour of this app. Notifications are vital as this app blocks the microphone from being used. The user **must** remain aware that microphone blocking is occurring and the main method Android has provided is through a posted notification with a minimal icon on the status bar and some information/link on the extended drawer.
I am looking at moving the passive jammer to a service but this can still suffer from both user action and OS abilities that dismiss notifications. It is debatable as to which way is appropriate (user desire vs app design) but i will try to err on the side of informed caution - this means that the notifications must remain, as blocking the microphone is an aggressive action.
n.b. API 28 (Pie) may make this sort of passive jammer irrelevant as the permissions for microphone use have changed, but it depends on if and how tracker devs may work around it.

**Comment by puppykickr** [comment]
I meant that some apps allow the selection of notifications on or off.

If selected 'on', the notification system acts as a way for the app to remain active, so that the system will not turn the app off.

In this case, the notification for the app can be turned off in the individual app settings on the device.

This gets rid of the banner notifications, while leaving the status bar notifications, and also allows the app to continuously run.

One such app is WaveUp.

**Comment by puppykickr** [comment]
I meant that some apps allow the selection of notifications on or off.

If selected 'on', the notification system acts as a way for the app to remain active, so that the system will not turn the app off.

In this case, the notification for the app can be turned off in the individual app settings on the device.

This gets rid of the banner notifications, while leaving the status bar notifications, and also allows the app to continuously run.

One such app is WaveUp.

**Comment by kaputnikGo** [comment]
Yes i get what you mean. The Waveup app uses a service (from quick look at source it looks like a foreground service) and that has different functions within the android OS, especially notifications. This type of service is what i may update the jammer app to run, after a bit more research into the state of things in API 28, specifically if theres an ability to bypass setRecordSilenced() and stop notifications from being dismissed.

**Comment by puppykickr** [comment]
The new version works well for me, as the issue with the volume has been
fixed.

Thank you.

The notification is not too bad.
I dont mind the one in the status bar at all.

It is just the banner notification that is a bit intrusive.

I see what you mean about the difference in foregroud and background apps
as far as notifications go, thank you for clarifying that for me.

Also, I was wondering if there was any chance of the addition of a camera
blocking feature as well?

Maybe even in a seperate app if need be, but it would be excellent if it
could be integrated into one app as an option.

Grant Ryan Swan
(puppykicker)
